name: Daniele Workflow
on:
  push:
jobs:
  Build:
    - name: Checkout
      uses: actions/checkout@v2
    runs-on: ubuntu-latest
    steps:
      - name: Preparing
        uses: joschi/setup-jdk@v2.3.0
        with:
          java-version: 17
      - name: Build
        run: ../../gradlew build