name: Alex Workflow
on:
  push:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: joschi/setup-jdk@v2.3.0
        with:
          java-version: 17
      - name: ls
        run: ls
      - name: build
        run: ./gradlew build